aspnet-core/src/MyCompanyName.AbpZeroTemplate.Web.Mvc/Areas/AppAreaName/Models/Layout/FooterViewModel.cs
using MyCompanyName.AbpZeroTemplate.Sessions.Dto;

namespace MyCompanyName.AbpZeroTemplate.Web.Areas.AppAreaName.Models.Layout
{
    public class FooterViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }

        public string GetProductNameWithEdition()
        {
            const string productName = "AbpZeroTemplate";

            if (LoginInformations.Tenant == null)
            {
                return productName;
            }

            if (LoginInformations.Tenant.Edition == null)
            {
                return productName;
            }

            if (LoginInformations.Tenant.Edition.DisplayName == null)
            {
                return productName;
            }

            return productName + " " + LoginInformations.Tenant.Edition.DisplayName;
        }
    }
}

aspnet-core/src/MyCompanyName.AbpZeroTemplate.Web.Mvc/Areas/AppAreaName/Models/Layout/LogoViewModel.cs
using MyCompanyName.AbpZeroTemplate.Sessions.Dto;
using Abp.Extensions;

namespace MyCompanyName.AbpZeroTemplate.Web.Areas.AppAreaName.Models.Layout
{
    public class LogoViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }

        public string LogoSkinOverride { get; set; }

        public string GetLogoUrl(string appPath, string logoSkin)
        {
            if (!LogoSkinOverride.IsNullOrEmpty())
            {
                logoSkin = LogoSkinOverride;
            }

            if (LoginInformations?.Tenant?.LogoId == null)
            {
                return appPath + $"Common/Images/app-logo-on-{logoSkin}.svg";
            }

            //id parameter is used to prevent caching only.
            return appPath + "TenantCustomization/GetLogo?id=" + LoginInformations.Tenant.LogoId;
        }
    }
}

aspnet-core/src/MyCompanyName.AbpZeroTemplate.Web.Mvc/Controllers/PaymentController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Abp;
using Abp.Runtime.Session;
using Microsoft.AspNetCore.Mvc;
using MyCompanyName.AbpZeroTemplate.Editions;
using MyCompanyName.AbpZeroTemplate.MultiTenancy;
using MyCompanyName.AbpZeroTemplate.MultiTenancy.Dto;
using MyCompanyName.AbpZeroTemplate.MultiTenancy.Payments;
using MyCompanyName.AbpZeroTemplate.MultiTenancy.Payments.Cache;
using MyCompanyName.AbpZeroTemplate.MultiTenancy.Payments.Dto;
using MyCompanyName.AbpZeroTemplate.Web.Models.Payment;

namespace MyCompanyName.AbpZeroTemplate.Web.Controllers
{
    public class PaymentController : AbpZeroTemplateControllerBase
    {
        private readonly IPaymentAppService _paymentAppService;
        private readonly ITenantRegistrationAppService _tenantRegistrationAppService;
        private readonly IPaymentCache _paymentCache;
        private readonly TenantManager _tenantManager;
        private readonly EditionManager _editionManager;
        private readonly ISubscriptionAppService _subscriptionAppService;

        public PaymentController(
            IPaymentAppService paymentAppService,
            ITenantRegistrationAppService tenantRegistrationAppService,
            IPaymentCache paymentCache,
            TenantManager tenantManager,
            EditionManager editionManager,
            ISubscriptionAppService subscriptionAppService)
        {
            _paymentAppService = paymentAppService;
            _tenantRegistrationAppService = tenantRegistrationAppService;
            _paymentCache = paymentCache;
            _tenantManager = tenantManager;
            _editionManager = editionManager;
            _subscriptionAppService = subscriptionAppService;
        }

        public async Task<IActionResult> Buy(int editionId, EditionPaymentType editionPaymentType, int? subscriptionStartType) //subscriptionStartType is used as int instead of SubscriptionStartType because MVC can not bind nullable enums
        {
            var edition = await _tenantRegistrationAppService.GetEdition(editionId);

            var model = new PaymentViewModel
            {
                Edition = edition,
                EditionPaymentType = editionPaymentType
            };

            if (subscriptionStartType.HasValue)
            {
                model.SubscriptionStartType = (SubscriptionStartType)subscriptionStartType.Value;
            }

            return View("Index", model);
        }

        public async Task<IActionResult> Upgrade(int upgradeEditionId, EditionPaymentType editionPaymentType)
        {
            return await UpgradeOrExtend(upgradeEditionId, editionPaymentType);
        }

        public async Task<IActionResult> Extend(int upgradeEditionId, EditionPaymentType editionPaymentType)
        {
            return await UpgradeOrExtend(upgradeEditionId, editionPaymentType);
        }

        [HttpPost]
        public async Task<CreatePaymentResponse> CreatePayment(CreatePaymentModel model)
        {
            var createPaymentResult = await _paymentAppService.CreatePayment(new CreatePaymentDto
            {
                PaymentPeriodType = model.PaymentPeriodType,
                EditionId = model.EditionId,
                EditionPaymentType = model.EditionPaymentType,
                SubscriptionPaymentGatewayType = model.Gateway
            });

            return createPaymentResult;
        }

        [HttpPost]
        public async Task CancelPayment(CancelPaymentModel model)
        {
            await _paymentAppService.CancelPayment(new CancelPaymentDto
            {
                Gateway = model.Gateway,
                PaymentId = model.PaymentId
            });
        }

        [HttpPost]
        public async Task<ActionResult> ExecutePayment(int editionId, PaymentPeriodType paymentPeriodType, SubscriptionPaymentGatewayType? gateway = null)
        {
            Check.NotNull(gateway, nameof(gateway));

            var edition = await _tenantRegistrationAppService.GetEdition(editionId);
            if (edition.IsFree)
            {
                throw new Exception("Can not execute payment for free editions!");
            }

            var paymentId = await ExecutePaymentAsync(editionId, paymentPeriodType, gateway.Value);
            return RedirectToAction("Register", "TenantRegistration", new
            {
                editionId = editionId,
                subscriptionStartType = SubscriptionStartType.Paid,
                gateway = gateway,
                paymentId = paymentId
            });
        }

        private async Task<string> ExecutePaymentAsync(int editionId, PaymentPeriodType paymentPeriodType, SubscriptionPaymentGatewayType gateway)
        {
            var data = Request.Form.ToDictionary(q => q.Key, q => string.Join(",", q.Value));

            var result = await _paymentAppService.ExecutePayment(new ExecutePaymentDto
            {
                EditionId = editionId,
                EditionPaymentType = EditionPaymentType.NewRegistration,
                Gateway = gateway,
                AdditionalData = data
            });

            var paymentId = result.GetId();
            _paymentCache.AddCacheItem(new PaymentCacheItem(gateway, paymentPeriodType, paymentId));

            return paymentId;
        }

        private async Task<IActionResult> UpgradeOrExtend(int upgradeEditionId, EditionPaymentType editionPaymentType)
        {
            var paymentInfo = await _paymentAppService.GetPaymentInfo(new PaymentInfoInput { UpgradeEditionId = upgradeEditionId });
            var edition = await _tenantRegistrationAppService.GetEdition(upgradeEditionId);

            if (editionPaymentType == EditionPaymentType.Upgrade && await UpgradeIsFree(upgradeEditionId))
            {
                await _subscriptionAppService.UpgradeTenantToEquivalentEdition(upgradeEditionId);
                return RedirectToAction("Index", "SubscriptionManagement", new { area = "AppAreaName" });
            }

            var model = new PaymentViewModel
            {
                Edition = edition,
                AdditionalPrice = paymentInfo.AdditionalPrice,
                EditionPaymentType = editionPaymentType
            };

            return View("Index", model);
        }

        private async Task<bool> UpgradeIsFree(int upgradeEditionId)
        {
            var tenant = await _tenantManager.GetByIdAsync(AbpSession.GetTenantId());

            if (!tenant.EditionId.HasValue)
            {
                throw new Exception("Tenant must be assigned to an Edition in order to upgrade !");
            }

            var currentEdition = (SubscribableEdition)await _editionManager.GetByIdAsync(tenant.EditionId.Value);
            var targetEdition = (SubscribableEdition)await _editionManager.GetByIdAsync(upgradeEditionId);
            var bothEditionsAreFree = targetEdition.IsFree && currentEdition.IsFree;
            var bothEditionsHasSamePrice = currentEdition.HasSamePrice(targetEdition);
            return bothEditionsAreFree || bothEditionsHasSamePrice;
        }
    }
}

aspnet-core/src/MyCompanyName.AbpZeroTemplate.Web.Mvc/Controllers/TenantRegistrationController.cs
using Abp.Authorization;
using Abp.Authorization.Users;
using Abp.Configuration;
using Abp.Configuration.Startup;
using Abp.Domain.Uow;
using Abp.Extensions;
using Abp.UI;
using Microsoft.AspNetCore.Mvc;
using MyCompanyName.AbpZeroTemplate.Authorization;
using MyCompanyName.AbpZeroTemplate.Authorization.Users;
using MyCompanyName.AbpZeroTemplate.Configuration;
using MyCompanyName.AbpZeroTemplate.Debugging;
using MyCompanyName.AbpZeroTemplate.Identity;
using MyCompanyName.AbpZeroTemplate.MultiTenancy;
using MyCompanyName.AbpZeroTemplate.MultiTenancy.Dto;
using MyCompanyName.AbpZeroTemplate.MultiTenancy.Payments;
using MyCompanyName.AbpZeroTemplate.Security;
using MyCompanyName.AbpZeroTemplate.Url;
using MyCompanyName.AbpZeroTemplate.Web.Security.Recaptcha;
using System.Threading.Tasks;
using Abp.Collections.Extensions;
using MyCompanyName.AbpZeroTemplate.Editions;
using MyCompanyName.AbpZeroTemplate.MultiTenancy.Payments.Dto;
using MyCompanyName.AbpZeroTemplate.Web.Models.TenantRegistration;

namespace MyCompanyName.AbpZeroTemplate.Web.Controllers
{
    public class TenantRegistrationController : AbpZeroTemplateControllerBase
    {
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly UserManager _userManager;
        private readonly AbpLoginResultTypeHelper _abpLoginResultTypeHelper;
        private readonly LogInManager _logInManager;
        private readonly SignInManager _signInManager;
        private readonly IWebUrlService _webUrlService;
        private readonly ITenantRegistrationAppService _tenantRegistrationAppService;
        private readonly IPasswordComplexitySettingStore _passwordComplexitySettingStore;

        public TenantRegistrationController(
            IMultiTenancyConfig multiTenancyConfig,
            UserManager userManager,
            AbpLoginResultTypeHelper abpLoginResultTypeHelper,
            LogInManager logInManager,
            SignInManager signInManager,
            IWebUrlService webUrlService,
            ITenantRegistrationAppService tenantRegistrationAppService,
            IPasswordComplexitySettingStore passwordComplexitySettingStore)
        {
            _multiTenancyConfig = multiTenancyConfig;
            _userManager = userManager;
            _abpLoginResultTypeHelper = abpLoginResultTypeHelper;
            _logInManager = logInManager;
            _signInManager = signInManager;
            _webUrlService = webUrlService;
            _tenantRegistrationAppService = tenantRegistrationAppService;
            _passwordComplexitySettingStore = passwordComplexitySettingStore;
        }

        public async Task<ActionResult> SelectEdition()
        {
            CheckTenantRegistrationIsEnabled();

            var output = await _tenantRegistrationAppService.GetEditionsForSelect();
            if (output.EditionsWithFeatures.IsNullOrEmpty())
            {
                return RedirectToAction("Register", "TenantRegistration");
            }

            var model = new EditionsSelectViewModel(output);

            return View(model);
        }

        public async Task<ActionResult> Register(int? editionId, SubscriptionStartType? subscriptionStartType = null, SubscriptionPaymentGatewayType? gateway = null, string paymentId = "")
        {
            CheckTenantRegistrationIsEnabled();

            var model = new TenantRegisterViewModel
            {
                PasswordComplexitySetting = await _passwordComplexitySettingStore.GetSettingsAsync(),
                SubscriptionStartType = subscriptionStartType,
                EditionPaymentType = EditionPaymentType.NewRegistration,
                Gateway = gateway,
                PaymentId = paymentId
            };

            if (editionId.HasValue)
            {
                model.EditionId = editionId.Value;
                model.Edition = await _tenantRegistrationAppService.GetEdition(editionId.Value);
            }

            ViewBag.UseCaptcha = UseCaptchaOnRegistration();

            return View(model);
        }

        [HttpPost]
        [UnitOfWork]
        public virtual async Task<ActionResult> Register(RegisterTenantInput model)
        {
            try
            {
                if (UseCaptchaOnRegistration())
                {
                    model.CaptchaResponse = HttpContext.Request.Form[RecaptchaValidator.RecaptchaResponseKey];
                }

                var result = await _tenantRegistrationAppService.RegisterTenant(model);

                CurrentUnitOfWork.SetTenantId(result.TenantId);

                var user = await _userManager.FindByNameAsync(AbpUserBase.AdminUserName);

                //Directly login if possible
                if (result.IsTenantActive && result.IsActive && !result.IsEmailConfirmationRequired &&
                    !_webUrlService.SupportsTenancyNameInUrl)
                {
                    var loginResult = await GetLoginResultAsync(user.UserName, model.AdminPassword, model.TenancyName);

                    if (loginResult.Result == AbpLoginResultType.Success)
                    {
                        await _signInManager.SignOutAsync();
                        await _signInManager.SignInAsync(loginResult.Identity, false);

                        SetTenantIdCookie(result.TenantId);

                        return Redirect(Url.Action("Index", "Home", new { area = "AppAreaName" }));
                    }

                    Logger.Warn("New registered user could not be login. This should not be normally. login result: " + loginResult.Result);
                }

                //Show result page
                var resultModel = ObjectMapper.Map<TenantRegisterResultViewModel>(result);

                resultModel.TenantLoginAddress = _webUrlService.SupportsTenancyNameInUrl
                    ? _webUrlService.GetSiteRootAddress(model.TenancyName).EnsureEndsWith('/') + "Account/Login"
                    : "";

                return View("RegisterResult", resultModel);
            }
            catch (UserFriendlyException ex)
            {
                ViewBag.UseCaptcha = UseCaptchaOnRegistration();
                ViewBag.ErrorMessage = ex.Message;

                var viewModel = new TenantRegisterViewModel
                {
                    PasswordComplexitySetting = await _passwordComplexitySettingStore.GetSettingsAsync(),
                    EditionId = model.EditionId,
                    SubscriptionStartType = model.SubscriptionStartType,
                    EditionPaymentType = EditionPaymentType.NewRegistration,
                    Gateway = model.Gateway,
                    PaymentId = model.PaymentId
                };

                if (model.EditionId.HasValue)
                {
                    viewModel.Edition = await _tenantRegistrationAppService.GetEdition(model.EditionId.Value);
                    viewModel.EditionId = model.EditionId.Value;
                }

                return View("Register", viewModel);
            }
        }

        private bool IsSelfRegistrationEnabled()
        {
            return SettingManager.GetSettingValueForApplication<bool>(AppSettings.TenantManagement.AllowSelfRegistration);
        }

        private void CheckTenantRegistrationIsEnabled()
        {
            if (!IsSelfRegistrationEnabled())
            {
                throw new UserFriendlyException(L("SelfTenantRegistrationIsDisabledMessage_Detail"));
            }

            if (!_multiTenancyConfig.IsEnabled)
            {
                throw new UserFriendlyException(L("MultiTenancyIsNotEnabled"));
            }
        }

        private bool UseCaptchaOnRegistration()
        {
            if (DebugHelper.IsDebug)
            {
                return false;
            }

            return SettingManager.GetSettingValueForApplication<bool>(AppSettings.TenantManagement.UseCaptchaOnRegistration);
        }

        private async Task<AbpLoginResult<Tenant, User>> GetLoginResultAsync(string usernameOrEmailAddress, string password, string tenancyName)
        {
            var loginResult = await _logInManager.LoginAsync(usernameOrEmailAddress, password, tenancyName);

            switch (loginResult.Result)
            {
                case AbpLoginResultType.Success:
                    return loginResult;
                default:
                    throw _abpLoginResultTypeHelper.CreateExceptionForFailedLoginAttempt(loginResult.Result, usernameOrEmailAddress, tenancyName);
            }
        }
    }
}

aspnet-core/src/MyCompanyName.AbpZeroTemplate.Web.Mvc/Views/TenantRegistration/Register.cshtml
@using Abp.Json
@using MyCompanyName.AbpZeroTemplate.MultiTenancy
@using MyCompanyName.AbpZeroTemplate.Web.Models.TenantRegistration
@addTagHelper *, PaulMiami.AspNetCore.Mvc.Recaptcha
@{
    ViewBag.DisableTenantChange = true;
}
@model TenantRegisterViewModel
@section Scripts
    {
    <script>
        window.passwordComplexitySetting = @Html.Raw(Model.PasswordComplexitySetting.ToJsonString(indented: true));
    </script>
    <environment names="Development">
        <script src="~/view-resources/Views/TenantRegistration/Register.js" asp-append-version="true"></script>
    </environment>

    <environment names="Staging,Production">
        <script src="~/view-resources/Views/TenantRegistration/Register.min.js" asp-append-version="true"></script>
    </environment>

    <recaptcha-script />
}
<div class="m-login m-login__signin">
    <div class="m-login__head">
        <h3 class="m-login__title">
            @L("TenantSignUp")
        </h3>
        <small>
            @if (Model.EditionId.HasValue)
            {
                <div class="hint text-center">(@L("Edition"): @Model.Edition.DisplayName)</div>
            }
        </small>
    </div>
    <form class="m-login__form m-form register-form" asp-action="Register" method="post" id="formTenantRegister">
        <input type="hidden" Name="EditionId" value="@Model.EditionId" />
        @if (Model.EditionId.HasValue)
        {
            <input type="hidden" Name="SubscriptionStartType" value="@Model.SubscriptionStartType" />
                <input type="hidden" name="EditionPaymentType" value="@Model.EditionPaymentType" />
                <input type="hidden" name="Gateway" value="@Model.Gateway" />
                <input type="hidden" name="PaymentId" value="@Model.PaymentId" />
        }

        @if (@ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger">
                <i class="fa fa-exclamation-triangle"></i> @ViewBag.ErrorMessage
            </div>
        }

        <h4 class="m-login__title">
            @L("TenantInformations")
        </h4>
        <div class="form-group m-form__group">
            <input class="form-control form-control m-input" type="text" placeholder="@L("TenancyName")" name="TenancyName" required maxlength="@Tenant.MaxTenancyNameLength" />
        </div>
        <div class="form-group m-form__group">
            <input class="form-control form-control m-input" type="text" placeholder="@L("Name")" name="Name" required maxlength="@MyCompanyName.AbpZeroTemplate.Authorization.Users.User.MaxNameLength" />
        </div>

        <h4 class="m-login__title m--margin-top-20">
            @L("AccountSettings")
        </h4>
        <div class="form-group m-form__group">
            <input class="form-control form-control m-input" type="email" placeholder="@L("AdminEmailAddress")" name="AdminEmailAddress" required maxlength="@MyCompanyName.AbpZeroTemplate.Authorization.Users.User.MaxEmailAddressLength" />
        </div>
        <div class="form-group m-form__group">
            <input class="form-control form-control m-input" type="password" autocomplete="off" id="AdminPassword" placeholder="@L("AdminPassword")" name="AdminPassword" required />
        </div>
        <div class="form-group m-form__group">
            <input class="form-control form-control m-input" type="password" autocomplete="off" placeholder="@L("AdminPasswordRepeat")" name="AdminPasswordRepeat" required />
        </div>
        @if (ViewBag.UseCaptcha)
        {

            <h4 class="m-login__title m--margin-top-20">
                @L("Captha_Hint")
            </h4>

            <div class="form-group margin-bottom-20">
                <recaptcha />
            </div>
        }
        <div class="m-portlet__body">
            <div class="m-login__form-action">
                <a asp-action="SelectEdition" asp-controller="TenantRegistration">
                    <button type="button" id="register-back-btn" class="btn btn-outline-primary  m-btn m-btn--pill m-btn--custom">@L("Back")</button>
                </a>
                <button type="submit" id="register-submit-btn" class="btn btn-primary m-btn m-btn--pill m-btn--custom m-btn--air">@L("Submit")</button>
            </div>
        </div>
    </form>
</div>    

aspnet-core/src/MyCompanyName.AbpZeroTemplate.Web.Mvc/Views/TenantRegistration/RegisterResult.cshtml
@model MyCompanyName.AbpZeroTemplate.Web.Models.TenantRegistration.TenantRegisterResultViewModel
@{
    ViewBag.DisableTenantChange = true;
}
<h4>@L("SuccessfullyRegistered").</h4>
<ul>
    <li><span class="text-muted">@L("TenancyName"):</span> @Model.TenancyName</li>
    <li><span class="text-muted">@L("Name"):</span> @Model.Name</li>
    <li><span class="text-muted">@L("UserName"):</span> @Model.UserName</li>
    <li><span class="text-muted">@L("EmailAddress"):</span> @Model.EmailAddress</li>
</ul>
<div>
    @if (Model.IsEmailConfirmationRequired)
    {
        <div class="alert alert-warning" role="alert">
            @L("ConfirmationMailSentPleaseClickLinkInTheEmail", Model.EmailAddress)
        </div>
    }
    @if (!Model.IsActive)
    {
        <div class="alert alert-warning" role="alert">
            @L("YourAccountIsWaitingToBeActivatedByAdmin")
        </div>
    }
    @if (!string.IsNullOrEmpty(Model.TenantLoginAddress))
    {
        <div class="alert alert-info" role="alert">
            @L("TenantRegistrationLoginInfo")<br />
            <a href="@Model.TenantLoginAddress">@Model.TenantLoginAddress</a>
        </div>
    }
</div>

aspnet-core/src/MyCompanyName.AbpZeroTemplate.Web.Mvc/Views/TenantRegistration/SelectEdition.cshtml
@using Abp.UI.Inputs
@using MyCompanyName.AbpZeroTemplate.Editions
@using MyCompanyName.AbpZeroTemplate.MultiTenancy.Payments.Dto
@model MyCompanyName.AbpZeroTemplate.Web.Models.TenantRegistration.EditionsSelectViewModel
@{
    ViewBag.DisableTenantChange = true;
    Layout = "_Layout";
    var isSetted = false;
    var editionIcons = new string[] { "flaticon-open-box", "flaticon-rocket", "flaticon-gift", "flaticon-confetti", "flaticon-cogwheel-2", "flaticon-app", "flaticon-coins", "flaticon-piggy-bank", "flaticon-bag", "flaticon-lifebuoy", "flaticon-technology-1", "flaticon-cogwheel-1", "flaticon-infinity", "flaticon-interface-5", "flaticon-squares-3", "flaticon-interface-6", "flaticon-mark", "flaticon-business", "flaticon-interface-7", "flaticon-list-2", "flaticon-bell", "flaticon-technology", "flaticon-squares-2", "flaticon-notes", "flaticon-profile", "flaticon-layers", "flaticon-interface-4", "flaticon-signs", "flaticon-menu-1", "flaticon-symbol" };
}
@section Styles
    {
    <link href="~/view-resources/Views/TenantRegistration/SelectEdition.css" rel="stylesheet" />
}
<div class="m-pricing-table-1 m-pricing-table-1--fixed">
    <div class="m-portlet">
        <div class="m-portlet__body">
            <div class="m-pricing-table-1__items row row-centered">
                @{ var i = 0;}
                @foreach (var editionWithFeatures in Model.EditionsWithFeatures)
                {
                    var edition = editionWithFeatures.Edition;

                    <div class="m-pricing-table-1__item col-lg-3 col-centered">

                        <div class="m-pricing-table-1__visual">
                            <div class="m-pricing-table-1__hexagon1"></div>
                            <div class="m-pricing-table-1__hexagon2"></div>
                            <span class="m-pricing-table-1__icon m--font-brand">
                                <i class="fa @editionIcons[i]"></i>
                            </span>
                        </div>

                        <span class="m-pricing-table-1__price">
                            @edition.DisplayName
                        </span>
                        <h2 class="m-pricing-table-1__subtitle">
                            @if (!edition.AnnualPrice.HasValue && !edition.MonthlyPrice.HasValue)
                            {

                                <text>@L("Free")</text>

                            }
                            else
                            {
                                <text><span class="m-pricing-table-1__label">$</span> @edition.MonthlyPrice?.ToString("N2") @L("PerMonth") / </text>
                                <text><span class="m-pricing-table-1__label">$</span> @edition.AnnualPrice?.ToString("N2") @L("PerYear")</text>
                            }
                        </h2>
                        <span class="m-pricing-table-1__description">
                            @foreach (var feature in Model.AllFeatures)
                            {
                                var featureValue = editionWithFeatures.FeatureValues.FirstOrDefault(f => f.Name == feature.Name);
                                if (feature.InputType.GetType() == typeof(CheckboxInputType))
                                {
                                    if (featureValue.Value == "true")
                                    {
                                        <i class="la la-check m--font-success"></i>
                                    }
                                    else
                                    {
                                        <i class="la la-times m--font-metal"></i>
                                    }
                                    <text> @feature.DisplayName</text>
                                }
                                else
                                {
                                    <i class="la la-check m--font-success"></i><text> @feature.DisplayName : @Html.Raw(featureValue.Value)</text>
                                }
                                <br/>
                            }
                        </span>
                        <div class="m-pricing-table-1__btn">
                            @if (AbpSession.UserId.HasValue)
                            {
                                if (!isSetted)
                                {
                                    if (edition.Id == Model.TenantEditionId)
                                    {
                                        isSetted = true;
                                    }

                                    <a class="btn btn-warning m-btn m-btn--custom m-btn--pill m-btn--wide m-btn--uppercase m-btn--bolder m-btn--sm disabled" href="#" disabled="disabled">
                                        @L("Upgrade")
                                    </a>
                                }
                                else
                                {
                                    <a class="btn btn-warning m-btn m-btn--custom m-btn--pill m-btn--wide m-btn--uppercase m-btn--bolder m-btn--sm" href="@Url.Action("Upgrade", "Payment", new {upgradeEditionId = edition.Id, editionPaymentType = EditionPaymentType.Upgrade})">
                                        @L("Upgrade")
                                    </a>
                                }
                            }
                            else
                            {
                                if (!edition.MonthlyPrice.HasValue && !edition.AnnualPrice.HasValue)
                                {
                                    <a class="btn btn-success m-btn m-btn--custom m-btn--pill m-btn--wide m-btn--uppercase m-btn--bolder m-btn--sm" href="@Url.Action("Register", "TenantRegistration", new {editionId = edition.Id, subscriptionStartType = SubscriptionStartType.Free})">
                                        @L("Start")
                                    </a>
                                }
                                else
                                {
                                    if (edition.TrialDayCount.HasValue)
                                    {
                                        <a class="btn btn-warning m-btn m-btn--custom m-btn--pill m-btn--wide m-btn--uppercase m-btn--bolder m-btn--sm" href="@Url.Action("Register", "TenantRegistration", new {editionId = edition.Id, subscriptionStartType = SubscriptionStartType.Trial})">
                                            @L("FreeTrial")
                                        </a>
                                    }

                                    <a class="btn btn-primary m-btn m-btn--custom m-btn--pill m-btn--wide m-btn--uppercase m-btn--bolder m-btn--sm" href="@Url.Action("Buy", "Payment", new {editionId = edition.Id, editionPaymentType = EditionPaymentType.NewRegistration, subscriptionStartType = (int) SubscriptionStartType.Paid})">
                                        @L("BuyNow")
                                    </a>
                                }
                            }
                        </div>
                    </div>

                    i++;
                }
            </div>
        </div>
    </div>
</div>